spring:
  application:
    name: txmq-client-b
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.9.33.193:3306/servera?serverTimezone=UTC
    username: root
    password: F@20dms2020
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.vv.txmqclientb.entity
server:
  port: 5021
rocketmq:
  producer:
    group: test-transaction
  name-server: 127.0.0.1:9876


